---
kind: pipeline
name: main

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: grafana/grafana-build
    tags:
    - latest
    - main
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

trigger:
  branch:
  - add-dockerfile
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_password
---
kind: signature
hmac: cceb836b0ef26bb8adc063aa5cb9fe7a12b561a5c4ca4d32db4e1081ee215bba

...
