name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20.2"
        cache: true
    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: projects/518247705518/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: github-actions@grafana-backstage-375210.iam.gserviceaccount.com
        access_token_lifetime: 300s
        export_environment_variables: true
        create_credentials_file: true
    - uses: docker/login-action@v2
      with:
        registry: 'europe-west4-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
    - run: "go run ./ci main --use-host-cache --publish-techdocs"
