name: PR

on:
  pull_request: {}

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20.2"
        cache: true
    - run: "go run ./ci main --use-host-cache"
